// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_-WSS9hLX9QmRHolB8pc4tpZI0x1IipI',
    appId: '1:390819678810:web:443f7c6f034d3278462663',
    messagingSenderId: '390819678810',
    projectId: 'catalog-dd7d2',
    authDomain: 'catalog-dd7d2.firebaseapp.com',
    storageBucket: 'catalog-dd7d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-C43aP9l4OzGrX3Mv_QOMkH5VOb-MiJE',
    appId: '1:390819678810:android:33c55b61ddcae257462663',
    messagingSenderId: '390819678810',
    projectId: 'catalog-dd7d2',
    storageBucket: 'catalog-dd7d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJDY04S3s_EnkYS6qHwr9-caYDIRa8kEY',
    appId: '1:390819678810:ios:5428aa156428921c462663',
    messagingSenderId: '390819678810',
    projectId: 'catalog-dd7d2',
    storageBucket: 'catalog-dd7d2.appspot.com',
    iosBundleId: 'com.example.catalog1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJDY04S3s_EnkYS6qHwr9-caYDIRa8kEY',
    appId: '1:390819678810:ios:a74b30e86c3e3c86462663',
    messagingSenderId: '390819678810',
    projectId: 'catalog-dd7d2',
    storageBucket: 'catalog-dd7d2.appspot.com',
    iosBundleId: 'com.example.catalog1.RunnerTests',
  );
}
